# Smart Traffic Light System Configuration

# Camera Settings
camera:
  # Camera sources - can be file paths, URLs, or device indices
  sources:
    - 0  # Default camera
    - "sample_videos/traffic1.mp4"
    - "sample_videos/traffic2.mp4"
  resolution:
    width: 1280
    height: 720
  fps: 30

# YOLO Model Settings
model:
  name: "yolov8n.pt"  # YOLOv8 nano for faster inference
  confidence: 0.5
  iou_threshold: 0.45
  device: "cpu"  # Use "cuda" if GPU available

# Traffic Analysis
traffic_analysis:
  # Vehicle classes to detect (COCO dataset class IDs)
  vehicle_classes: [2, 3, 5, 7]  # car, motorcycle, bus, truck
  
  # Traffic density thresholds
  density_thresholds:
    low: 5
    medium: 15
    high: 30
  
  # Analysis window (seconds)
  analysis_window: 10
  
  # ROI (Region of Interest) for each direction
  # Format: [x1, y1, x2, y2] as percentage of frame
  roi:
    north: [0.1, 0.1, 0.9, 0.4]
    south: [0.1, 0.6, 0.9, 0.9]
    east: [0.6, 0.1, 0.9, 0.9]
    west: [0.1, 0.1, 0.4, 0.9]

# Traffic Light Timing
traffic_light:
  # Default timing (seconds)
  default_timing:
    green: 30
    yellow: 5
    red: 35
  
  # Dynamic timing ranges
  timing_ranges:
    green_min: 15
    green_max: 60
    yellow: 5  # Fixed
    red_min: 10
    red_max: 45
  
  # Cycle time limits
  min_cycle_time: 60
  max_cycle_time: 180

# Web Dashboard
dashboard:
  host: "0.0.0.0"
  port: 5000
  debug: false

# Logging
logging:
  level: "INFO"
  file: "logs/traffic_system.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Data Storage
data:
  save_detections: true
  save_images: false
  output_dir: "data/output"
  database: "data/traffic_data.db"